version: '3.7'
services:
  app:
    container_name: rails524
    tty: true # binding.pryするために必要
    stdin_open: true # binding.pryするために必要
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/zasetsu_norikoe_app # ローカルのディレクトリをコンテナ上にマウントする
    ports:
      - '3000:3000'
  db:
    image: mysql:5.7
    # 下記 M1 Mac用。M1 Macの場合は上記imageをコメントアウト後、下記のコメントアウトを外してdocker起動
    # image: mysql:5.7@sha256:b3b2703de646600b008cbb2de36b70b21e51e7e93a7fca450d2b08151658b2dd
    container_name: mysql57
    volumes:
      - ./docker/mysql57/data:/var/lib/mysql #データの永続化
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password

