version: '3.7'
services:
  app:
    container_name: rails524
    tty: true # binding.pryするために必要
    stdin_open: true # binding.pryするために必要
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/zasetsu_norikoe_app # ローカルのディレクトリをコンテナ上にマウントする
    ports:
      - '3000:3000'
  db:
    image: mysql:5.7
    container_name: mysql57
    volumes:
      - ./docker/mysql57/data:/var/lib/mysql #データの永続化
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password

