# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Run RuboCop and RSpec

on: push

jobs:
  rubocop:
    # ジョブを実行する仮想マシンを選択（ubuntu/macOS/Windows)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6.6
    - name: Run Rubocop
      run: |
        gem install rubocop rubocop-performance rubocop-rails rubocop-rspec
        rubocop

  rspec:
    # ジョブを実行する仮想マシンを選択（ubuntu/macOS/Windows)
    # MySQL5.7を使用したいので、16.04を指定
    runs-on: ubuntu-16.04
    env:
      RAILS_ENV: test
      DB_USER: root
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_PASSWORD: root # TODO: GitHub Actions では、MYSQL_ROOT_PASSWORDで指定しても、パスワードがrootになってしまう。
    services:
      db:
        image: mysql:5.7
        env:
          MYSQL_USER: root
#          MYSQL_ROOT_PASSWORD: password TODO: 2021/03/28 なぜかパスワードの設定ができなくなってしまったので、コメントアウト
        ports:
          - 3306:3306
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.6
      - name: Cache gems
        uses: actions/cache@preview
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-
      - name: bundle install
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3 --path vendor/bundle
      - name: DB Setup
        run: |
          sudo systemctl start mysql
          bundle exec rails db:create
          bundle exec rails db:migrate
      - name: Run RSpec
        run: bundle exec rspec

        # TODO: workflowのデバッグを行いたい場合は以下を使う
#      - name: Debug
#        if: ${{ failure() }}
#        uses: mxschmitt/action-tmate@v3
